
# SPOT HelperFunctions SelfTest v1.0
#
#  Version 1.0 - 02.07.2026 - initial version
#
#
# Helper Functions
################################################################################################################################################################
################################################################################################################################################################
function Write-STLog {
    Param (
        [Parameter(Mandatory=$true)]
        [ValidateNotNullOrEmpty()]
        [String]
        $Message, # The log entry to be written
        [Parameter(Mandatory=$false)]
        [bool]
        $Output = $true, # set the function to write only in the log file and not also in the console putput
        [Parameter(Mandatory=$false)]
        [String]
        $LogPath = "$env:windir\Temp\SelfTest.log" # The Path of the Log file generated by the current script
        )

    $ErrorActionPreference = "SilentlyContinue"

    # Format Date for our Log File 
    $FormattedDate = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    # Write log entry to $LogPath 
    # https://stackoverflow.com/questions/23999761/multiple-powershell-scripts-writing-to-same-file

    while ($true) {
        Try {
            $sw = New-Object -TypeName System.IO.StreamWriter($LogPath, $true)
            $sw.WriteLine("$FormattedDate :: $Message")
            $sw.Close()
            Break
        }
        Catch {}
    }

    # "$FormattedDate :: $Message" | Out-File -FilePath $LogPath -Append -Encoding ascii
    if ($Output) {
        # Also write the log entry to output, to have the same logging in the Runbook as well
        Write-Output "$FormattedDate :: $Message"
    }

    # clear any errors, most likely while accessing the file
    $Error.Clear()
} # end of Write-STLog function

######################################################################################################################
function Start-STFunction {
    Param (
        [Parameter(Mandatory=$true)]
        [ValidateNotNullOrEmpty()]
        [string]
        $InputVariable # 
    )

    # show parameter value
    Write-STLog "Parameter InputVariable: $InputVariable."
    
    # test custom Write-Host
    Write-Host "Write-Host with colors execution test" -ForegroundColor Blue -BackgroundColor Yelllow

    # test for variable cross-bleed
    Write-Output "Test against cross-bleeding of normal variables. Initial value for CBTest is: $CBTest."
    $CBTest = "CrossBleeding!!!"
    Write-Output "Test against cross-bleeding of global variables. Initial value for GCBTest is: $GCBTest."
    $Global:GCBTest = "GlobalCrossBleeding!!!"

    # test ExecPath
    Write-STLog "Current working folder: $((Get-Location).Path)."

    # test the access to the OrchVars
    Write-STLog "OrchVars.TestVariable value: $($OrchVars.TestVariable)."
    Write-STLog "OrchVars.TestCredential UserName: $($OrchVars.TestCredential.GetNetworkCredential().UserName)."

    # testing safe exit handling inside the execution runspace
    exit 0
    
} # end of Start-STFunction function

######################################################################################################################
function Check-STResults {
    Param (
        [Parameter(Mandatory=$true)]
        [ValidateNotNullOrEmpty()]
        [hashtable]
        # first parameter
        $PublishedVars
    )

    # check if one parameter is equal to the other parameter
    Write-STLog "Starting function CheckSelfTestResults."
    Write-STLog "###########################################################"

    #$PublishedVars | Out-string

    ######################################################################################################################
    ####################################################################################
    Write-STLog "TestRbkLCL > Step1"
    ######################################
    if ($PublishedVars.LocalStepTest -like "*InputVariable: STRING_TEST_VARIABLE_L*") {
        Write-STLog " > Local Step Type                 : VALIDATED"
        Write-STLog " > Assign parameter in local Step  : VALIDATED"
    }
    else {
        Write-STLog " > Local Step Type                 : FAILED"
        Write-STLog " > Assign parameter in local Step  : FAILED"
    }
    if ($PublishedVars.LocalStepTest -like "*TestVariable value: TestValue*") {
        Write-STLog " > Access to OrchVars in local Step  : VALIDATED"
    }
    else {
        Write-STLog " > Access to OrchVars in local Step  : FAILED"
    }

    ####################################################################################
    Write-STLog "TestRbkLCL > Step2"
    ######################################
    if ($PublishedVars.RemoteStepTest -like "*InputVariable: STRING_TEST_VARIABLE_R*") {
        Write-STLog " > Remote Step Type                 : VALIDATED"
        Write-STLog " > Assign parameter in remote Step  : VALIDATED"
    }
    else {
        Write-STLog " > Remote Step Type                 : FAILED"
        Write-STLog " > Assign parameter in remote Step  : FAILED"
    }
    if ($PublishedVars.RemoteStepTest -like "*TestVariable value: TestValue*") {
        Write-STLog " > Access to OrchVars in remote Step  : VALIDATED"
    }
    else {
        Write-STLog " > Access to OrchVars in remote Step  : FAILED"
    }

    ####################################################################################
    Write-STLog "TestRbkLCL > Step3"
    ######################################
    if ($PublishedVars.RemoteSJStepTest -like "*InputVariable: STRING_TEST_VARIABLE_RSJ*") {
        Write-STLog " > RemoteSJ Step Type                 : VALIDATED"
        Write-STLog " > Assign parameter in remoteSJ Step  : VALIDATED"
    }
    else {
        Write-STLog " > RemoteSJ Step Type                 : FAILED"
        Write-STLog " > Assign parameter in remoteSJ Step  : FAILED"
    }
    if ($PublishedVars.RemoteSJStepTest -like "*TestVariable value: TestValue*") {
        Write-STLog " > Access to OrchVars in remoteSJ Step  : VALIDATED"
    }
    else {
        Write-STLog " > Access to OrchVars in remoteSJ Step  : FAILED"
    }

    ####################################################################################
    Write-STLog "TestRbkLCL > Step4"
    ######################################
    if ($PublishedVars.RemoteWMIStepTest -like "*InputVariable: STRING_TEST_VARIABLE_RWMI*") {
        Write-STLog " > RemoteWMI Step Type                 : VALIDATED"
        Write-STLog " > Assign parameter in remoteWMI Step  : VALIDATED"
    }
    else {
        Write-STLog " > RemoteWMI Step Type                 : FAILED"
        Write-STLog " > Assign parameter in remoteWMI Step  : FAILED"
    }
    if ($PublishedVars.RemoteWMIStepTest -like "*TestVariable value: TestValue*") {
        Write-STLog " > Access to OrchVars in remoteWMI Step  : VALIDATED"
    }
    else {
        Write-STLog " > Access to OrchVars in remoteWMI Step  : FAILED"
    }

    ####################################################################################
    Write-STLog "TestRbkLCL > Step5"
    ######################################
    if ($PublishedVars.RemotePSEStepTest -like "*InputVariable: STRING_TEST_VARIABLE_RPsExec*") {
        Write-STLog " > RemotePSE Step Type                 : VALIDATED"
        Write-STLog " > Assign parameter in remotePSE Step  : VALIDATED"
    }
    else {
        Write-STLog " > RemotePSE Step Type                 : FAILED"
        Write-STLog " > Assign parameter in remotePSE Step  : FAILED"
    }
    if ($PublishedVars.RemotePSEStepTest -like "*TestVariable value: TestValue*") {
        Write-STLog " > Access to OrchVars in remotePSE Step  : VALIDATED"
    }
    else {
        Write-STLog " > Access to OrchVars in remotePSE Step  : FAILED"
    }

    ####################################################################################
    Write-STLog "TestRbkLCL > Step6"
    ######################################
    if ($PublishedVars.RemoteOWMIStepTest -like "*InputVariable: STRING_TEST_VARIABLE_ROWMI*") {
        Write-STLog " > RemoteOWMI Step Type                 : VALIDATED"
        Write-STLog " > Assign parameter in remoteOWMI Step  : VALIDATED"
    }
    else {
        Write-STLog " > RemoteOWMI Step Type                 : FAILED"
        Write-STLog " > Assign parameter in remoteOWMI Step  : FAILED"
    }
    if ($PublishedVars.RemoteOWMIStepTest -like "*TestVariable value: TestValue*") {
        Write-STLog " > Access to OrchVars in remoteOWMI Step  : VALIDATED"
    }
    else {
        Write-STLog " > Access to OrchVars in remoteOWMI Step  : FAILED"
    }

    ######################################################################################################################
    ####################################################################################
    Write-STLog "TestRbkLCLRem1 > Step1"
    ######################################
    if ($PublishedVars.LocalStepOutput_NestedLocalRunbook -like "*InputVariable: STRING_TEST_VARIABLE_CallingRBValue1*") {
        Write-STLog " > Local Step Type in Local Nested Runbook                     : VALIDATED"
        Write-STLog " > Assign parameter in Local Step Type in Local Nested Runbook : VALIDATED"
    }
    else {
        Write-STLog " > Local Step Type in Local Nested Runbook                     : FAILED"
        Write-STLog " > Assign parameter in Local Step Type in Local Nested Runbook : FAILED"
    }
    if ($PublishedVars.LocalStepOutput_NestedLocalRunbook -like "*TestVariable value: TestValue*") {
        Write-STLog " > Access to OrchVars in Local Step Type in Local Nested Runbook  : VALIDATED"
    }
    else {
        Write-STLog " > Access to OrchVars in Local Step Type in Local Nested Runbook  : FAILED"
    }

    ####################################################################################
    Write-STLog "TestRbkLCLRem1 > Step2"
    ######################################
    if ($PublishedVars.RemoteStepOutput_NestedLocalRunbook -like "*InputVariable: STRING_TEST_VARIABLE_DefaultRBValue2*") {
        Write-STLog " > Remote Step Type in Local Nested Runbook                     : VALIDATED"
        Write-STLog " > Assign parameter in Remote Step Type in Local Nested Runbook : VALIDATED"
    }
    else {
        Write-STLog " > Remote Step Type in Local Nested Runbook                     : FAILED"
        Write-STLog " > Assign parameter in Remote Step Type in Local Nested Runbook : FAILED"
    }
    if ($PublishedVars.RemoteStepOutput_NestedLocalRunbook -like "*TestVariable value: TestValue*") {
        Write-STLog " > Access to OrchVars in Remote Step Type in Local Nested Runbook  : VALIDATED"
    }
    else {
        Write-STLog " > Access to OrchVars in Remote Step Type in Local Nested Runbook  : FAILED"
    }

    ######################################################################################################################
    ####################################################################################
    Write-STLog "TestRbkLCLRem2 > Step1"
    ######################################
    if ($PublishedVars.LocalStepOutput_NestedRemoteRunbook -like "*InputVariable: STRING_TEST_VARIABLE_DefaultRBValue1*") {
        Write-STLog " > Local Step Type in Remote Nested Runbook                     : VALIDATED"
        Write-STLog " > Assign parameter in Local Step Type in Remote Nested Runbook : VALIDATED"
    }
    else {
        Write-STLog " > Local Step Type in Remote Nested Runbook                     : FAILED"
        Write-STLog " > Assign parameter in Local Step Type in Remote Nested Runbook : FAILED"
    }
    if ($PublishedVars.LocalStepOutput_NestedRemoteRunbook -like "*TestVariable value: TestValue*") {
        Write-STLog " > Access to OrchVars in Local Step Type in Remote Nested Runbook  : VALIDATED"
    }
    else {
        Write-STLog " > Access to OrchVars in Local Step Type in Remote Nested Runbook  : FAILED"
    }

    ####################################################################################
    Write-STLog "TestRbkLCLRem2 > Step2"
    ######################################
    if ($PublishedVars.RemoteStepOutput_NestedRemoteRunbook -like "*InputVariable: STRING_TEST_VARIABLE_RemoteCallingRBValue2*") {
        Write-STLog " > Remote Step Type in Remote Nested Runbook                     : VALIDATED"
        Write-STLog " > Assign parameter in Remote Step Type in Remote Nested Runbook : VALIDATED"
    }
    else {
        Write-STLog " > Remote Step Type in Remote Nested Runbook                     : FAILED"
        Write-STLog " > Assign parameter in Remote Step Type in Remote Nested Runbook : FAILED"
    }
    if ($PublishedVars.RemoteStepOutput_NestedRemoteRunbook -like "*TestVariable value: TestValue*") {
        Write-STLog " > Access to OrchVars in Remote Step Type in Remote Nested Runbook  : VALIDATED"
    }
    else {
        Write-STLog " > Access to OrchVars in Remote Step Type in Remote Nested Runbook  : FAILED"
    }

    ######################################################################################################################
    ####################################################################################
    Write-STLog "TestRbkLCLRem3 > Step1"
    ######################################
    if ($PublishedVars.LocalStepOutput_NestedRemoteWMIRunbook -like "*InputVariable: STRING_TEST_VARIABLE_RemoteWMICallingRBValue1*") {
        Write-STLog " > Local Step Type in RemoteWMI Nested Runbook                     : VALIDATED"
        Write-STLog " > Assign parameter in Local Step Type in RemoteWMI Nested Runbook : VALIDATED"
    }
    else {
        Write-STLog " > Local Step Type in RemoteWMI Nested Runbook                     : FAILED"
        Write-STLog " > Assign parameter in Local Step Type in RemoteWMI Nested Runbook : FAILED"
    }
    if ($PublishedVars.LocalStepOutput_NestedRemoteWMIRunbook -like "*TestVariable value: TestValue*") {
        Write-STLog " > Access to OrchVars in Local Step Type in RemoteWMI Nested Runbook  : VALIDATED"
    }
    else {
        Write-STLog " > Access to OrchVars in Local Step Type in RemoteWMI Nested Runbook  : FAILED"
    }

    ####################################################################################
    Write-STLog "TestRbkLCLRem3 > Step2"
    ######################################
    if ($PublishedVars.RemoteStepOutput_NestedRemoteWMIRunbook -like "*InputVariable: STRING_TEST_VARIABLE_RemoteWMICallingRBValue2*") {
        Write-STLog " > Remote Step Type in RemoteWMI Nested Runbook                     : VALIDATED"
        Write-STLog " > Assign parameter in Remote Step Type in RemoteWMI Nested Runbook : VALIDATED"
    }
    else {
        Write-STLog " > Remote Step Type in RemoteWMI Nested Runbook                     : FAILED"
        Write-STLog " > Assign parameter in Remote Step Type in RemoteWMI Nested Runbook : FAILED"
    }
    if ($PublishedVars.RemoteStepOutput_NestedRemoteWMIRunbook -like "*TestVariable value: TestValue*") {
        Write-STLog " > Access to OrchVars in Remote Step Type in RemoteWMI Nested Runbook  : VALIDATED"
    }
    else {
        Write-STLog " > Access to OrchVars in Remote Step Type in RemoteWMI Nested Runbook  : FAILED"
    }

    ######################################################################################################################
    ####################################################################################
    Write-STLog "TestRbkLCLRem4 > Step1"
    ######################################
    if ($PublishedVars.LocalStepOutput_NestedRemotePSERunbook -like "*InputVariable: STRING_TEST_VARIABLE_RemotePSECallingRBValue1*") {
        Write-STLog " > Local Step Type in RemotePSE Nested Runbook                     : VALIDATED"
        Write-STLog " > Assign parameter in Local Step Type in RemotePSE Nested Runbook : VALIDATED"
    }
    else {
        Write-STLog " > Local Step Type in RemotePSE Nested Runbook                     : FAILED"
        Write-STLog " > Assign parameter in Local Step Type in RemotePSE Nested Runbook : FAILED"
    }
    if ($PublishedVars.LocalStepOutput_NestedRemotePSERunbook -like "*TestVariable value: TestValue*") {
        Write-STLog " > Access to OrchVars in Local Step Type in RemotePSE Nested Runbook  : VALIDATED"
    }
    else {
        Write-STLog " > Access to OrchVars in Local Step Type in RemotePSE Nested Runbook  : FAILED"
    }

    ####################################################################################
    Write-STLog "TestRbkLCLRem4 > Step2"
    ######################################
    if ($PublishedVars.RemoteStepOutput_NestedRemotePSERunbook -like "*InputVariable: STRING_TEST_VARIABLE_RemotePSECallingRBValue2*") {
        Write-STLog " > Remote Step Type in RemotePSE Nested Runbook                     : VALIDATED"
        Write-STLog " > Assign parameter in Remote Step Type in RemotePSE Nested Runbook : VALIDATED"
    }
    else {
        Write-STLog " > Remote Step Type in RemotePSE Nested Runbook                     : FAILED"
        Write-STLog " > Assign parameter in Remote Step Type in RemotePSE Nested Runbook : FAILED"
    }
    if ($PublishedVars.RemoteStepOutput_NestedRemotePSERunbook -like "*TestVariable value: TestValue*") {
        Write-STLog " > Access to OrchVars in Remote Step Type in RemotePSE Nested Runbook  : VALIDATED"
    }
    else {
        Write-STLog " > Access to OrchVars in Remote Step Type in RemotePSE Nested Runbook  : FAILED"
    }

    ######################################################################################################################
    ####################################################################################
    Write-STLog "TestRbkLCLRem5 > Step1"
    ######################################
    if ($PublishedVars.LocalStepOutput_NestedRemoteOWMIRunbook -like "*InputVariable: STRING_TEST_VARIABLE_RemoteOWMICallingRBValue1*") {
        Write-STLog " > Local Step Type in RemoteOWMI Nested Runbook                     : VALIDATED"
        Write-STLog " > Assign parameter in Local Step Type in RemoteOWMI Nested Runbook : VALIDATED"
    }
    else {
        Write-STLog " > Local Step Type in RemoteOWMI Nested Runbook                     : FAILED"
        Write-STLog " > Assign parameter in Local Step Type in RemoteOWMI Nested Runbook : FAILED"
    }
    if ($PublishedVars.LocalStepOutput_NestedRemoteOWMIRunbook -like "*TestVariable value: TestValue*") {
        Write-STLog " > Access to OrchVars in Local Step Type in RemoteOWMI Nested Runbook  : VALIDATED"
    }
    else {
        Write-STLog " > Access to OrchVars in Local Step Type in RemoteOWMI Nested Runbook  : FAILED"
    }

    ####################################################################################
    Write-STLog "TestRbkLCLRem5 > Step2"
    ######################################
    if ($PublishedVars.RemoteStepOutput_NestedRemoteOWMIRunbook -like "*InputVariable: STRING_TEST_VARIABLE_RemoteOWMICallingRBValue2*") {
        Write-STLog " > Remote Step Type in RemoteOWMI Nested Runbook                     : VALIDATED"
        Write-STLog " > Assign parameter in Remote Step Type in RemoteOWMI Nested Runbook : VALIDATED"
    }
    else {
        Write-STLog " > Remote Step Type in RemoteOWMI Nested Runbook                     : FAILED"
        Write-STLog " > Assign parameter in Remote Step Type in RemoteOWMI Nested Runbook : FAILED"
    }
    if ($PublishedVars.RemoteStepOutput_NestedRemoteOWMIRunbook -like "*TestVariable value: TestValue*") {
        Write-STLog " > Access to OrchVars in Remote Step Type in RemoteOWMI Nested Runbook  : VALIDATED"
    }
    else {
        Write-STLog " > Access to OrchVars in Remote Step Type in RemoteOWMI Nested Runbook  : FAILED"
    }

    ######################################################################################################################
    Write-STLog "###########################################################"
    Write-STLog "Finished function Check-STResults"

} # end of Check-STResults function
