StepTypeDefinitions:
    RunbookStepParameters: # the step parameters needed by the type function
        PowershellCommandLocal:
            CommandName:   # the name of the command (script or function name) to be executed; it must be already loaded/available
                Mandatory: True
            CommandParameters: # the parameters for the command to be executed
                Mandatory: False
            ExecPath: # the execution path for the payload script/function
                Mandatory: False
            VariablesToPublish: # the variable names to be published; they can be any variables defined in the function
                Mandatory: False
        PowershellCommandRemote:
            CommandName: # the name of the command (script or function name) to be executed; it must be already loaded/available
                Mandatory: True
            CommandParameters:   # the parameters for the command to be executed
                Mandatory: False
            ExecPath: # the execution path for the payload script/function
                Mandatory: False
            VariablesToPublish: # the variable names to be published; they can be any variables defined in the script
                Mandatory: False
            RemoteComputer: # the hostname or IP of the remote computer on which the script shall be executed
                Mandatory: True
            Credential: # the credential to be used to connect to the remote computer
                Mandatory: True
            UseSSL: # to create the WinRM session with SSL
                Mandatory: False
        PowershellCommandRemoteSJ:
            CommandName: # the name of the command (script or function name) to be executed; it must be already loaded/available
                Mandatory: True
            CommandParameters:   # the parameters for the command to be executed
                Mandatory: False
            ExecPath: # the execution path for the payload script/function
                Mandatory: False
            VariablesToPublish: # the variable names to be published; they can be any variables defined in the script
                Mandatory: False
            RemoteComputer: # the hostname or IP of the remote computer on which the script shall be executed
                Mandatory: True
            Credential: # the credential to be used to connect to the remote computer
                Mandatory: True
            AsUser: # the alternative credential to be used to execute the payload on the remote computer
                Mandatory: False
            AsSystem: # specify if the remote code is to be executed as local system on the target computer
                Mandatory: False
            UseSSL: # to create the WinRM session with SSL
                Mandatory: False
        PowershellCommandRemoteWMI:
            CommandName: # the name of the command (script or function name) to be executed; it must be already loaded/available
                Mandatory: True
            CommandParameters:   # the parameters for the command to be executed
                Mandatory: False
            ExecPath: # the execution path for the payload script/function
                Mandatory: False
            VariablesToPublish: # the variable names to be published; they can be any variables defined in the script
                Mandatory: False
            RemoteComputer: # the hostname or IP of the remote computer on which the script shall be executed
                Mandatory: True
            Credential: # the credential to be used to connect to the remote computer
                Mandatory: True
        PowershellCommandRemotePsExec:
            CommandName: # the name of the command (script or function name) to be executed; it must be already loaded/available
                Mandatory: True
            CommandParameters:   # the parameters for the command to be executed
                Mandatory: False
            ExecPath: # the execution path for the payload script/function
                Mandatory: False
            VariablesToPublish: # the variable names to be published; they can be any variables defined in the script
                Mandatory: False
            RemoteComputer: # the hostname or IP of the remote computer on which the script shall be executed
                Mandatory: True
            Credential: # the credential to be used to connect to the remote computer
                Mandatory: True
            AsSystem: # specify if the remote code is to be executed as local system on the target computer
                Mandatory: False
        PowershellCommandRemoteOWMI:
            CommandName: # the name of the command (script or function name) to be executed; it must be already loaded/available
                Mandatory: True
            CommandParameters:   # the parameters for the command to be executed
                Mandatory: False
            ExecPath: # the execution path for the payload script/function
                Mandatory: False
            VariablesToPublish: # the variable names to be published; they can be any variables defined in the script
                Mandatory: False
            RemoteComputer: # the hostname or IP of the remote computer on which the script shall be executed
                Mandatory: True
            Credential: # the credential to be used to connect to the remote computer
                Mandatory: True

